weather/weather/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from weatherApp import views as weatherApp_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weatherapp/', include('weatherApp.urls', namespace='weatherapp')),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework'))]

weather/weatherApp/urls.py
from django.contrib.auth import views as auth_views
from weatherApp.views import registration, activate, account_activation_sent, home
from django.conf.urls import url, include
from django.core.urlresolvers import reverse

from rest_framework.urlpatterns import format_suffix_patterns
from .views import CreateView, RecordsView



urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^register/$', registration, name='registration',),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),

    url(r'^login/$', auth_views.login, {'template_name': 'admin/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/weatherapp/login/'}, name='logout'),

    url(r'^api/retrieve/$', RecordsView.as_view(), name="retrieve"),
    url(r'^api/create/$', CreateView.as_view(), name="create"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

weather/weatherApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
    	if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    email_confirmed = models.BooleanField(default=False)
    
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    
    class Meta:
        verbose_name = 'Weather App User'
        verbose_name_plural = 'Weather App Users'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin




class Weather(models.Model):
    date = models.DateTimeField(primary_key=True)
    min_temp = models.FloatField()
    max_temp = models.FloatField()
    wind = models.FloatField()
    rain = models.CharField(max_length=30, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Weather Record'
        verbose_name_plural = 'Weather Records'

    def __unicode__(self):
       return "%s" % (self.date)

weather/weatherApp/forms.py
from django import forms
from weatherApp.admin import UserCreationForm
from weatherApp.models import MyUser

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = MyUser
        fields = ('email', 'password1', 'password2', )

weather/weatherApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from weatherApp.forms import RegistrationForm
from weatherApp.tokens import account_activation_token
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from django.core.mail import send_mail
from weatherApp.models import MyUser
from django.contrib.auth import login
from django.core.urlresolvers import reverse

from rest_framework import generics
from .serializers import WeatherSerializer
from .models import Weather
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, IsAdminUser

from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime



def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            print user.email
            print str(user.email)
            send_mail(subject, message, 'popoolaebenezer@gmail.com', [str(user.email),], fail_silently=False)
            return redirect('weatherapp:account_activation_sent')
    else:
        form = RegistrationForm()
    return render(request, 'registration/registration.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = MyUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, MyUser.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'registration/account_activation_invalid.html')

def account_activation_sent(request):
    return render(request, 'registration/account_activation_sent.html')


@login_required(login_url='/weatherapp/login/')
def home(request):
    obj = Weather.objects.filter(date__gte=datetime.now())

    page = request.GET.get('page', 1)

    paginator = Paginator(obj, 3)
    try:
        weather = paginator.page(page)
    except PageNotAnInteger:
        weather = paginator.page(1)
    except EmptyPage:
        weather = paginator.page(paginator.num_pages)

    return render(request, 'weatherApp/home.html', {'weather': weather})


class CreateView(generics.ListCreateAPIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,IsAdminUser)
    """This class defines the create behavior of our rest api."""
    queryset = Weather.objects.all()
    serializer_class = WeatherSerializer

    def perform_create(self, serializer):
        """Save the post data when creating a new bucketlist."""
        serializer.save()

class RecordsView(generics.ListAPIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    permission_classes = (IsAuthenticated,)
    """This class defines the create behavior of our rest api."""
    queryset = Weather.objects.all()
    serializer_class = WeatherSerializer

weather/templates/weatherApp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'weatherapp:logout' %}">logout</a>
      {% else %}
        <a href="{% url 'weatherapp:login' %}">login</a> / <a href="{% url 'weatherapp:register' %}">Register</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>

weather/templates/weatherApp/home.html
{% extends 'admin/base.html' %}

{% block branding %}
   <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
                 <a class="navbar-brand" href="#">Weather Result</a>
            </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                   <a href="{% url 'weatherapp:logout' %}">logout</a>
               {% else %}
                  <a href="{% url 'weatherapp:login' %}">login</a> / <a href="{% url 'weatherapp:register' %}">Register</a>
              {% endif %}

            </ul>
          </div><!--/.nav-collapse -->

      </div><!--/.container-fluid -->
</nav>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block content %}

  <table class="table table-bordered">
  <thead>
    <tr>
      <th>Date and Time</th>
      <th>Minimum Temperature</th>
      <th>Maximum Temperature</th>
      <th>Wind</th>
      <th>Rain</th>
    </tr>
  </thead>
  <tbody>
    {% for entry in weather %}
      <tr>
        <td>{{ entry.date }}</td>
        <td>{{ entry.min_temp }}</td>
        <td>{{ entry.max_temp }}</td>
        <td>{{ entry.wind }}</td>
        <td>{{ entry.rain }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<footer>
{% if weather.has_other_pages %}
 <nav>
  <ul class="pagination">
    {% if weather.has_previous %}
      <li><a href="?page={{ weather.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in weather.paginator.page_range %}
      {% if weather.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if weather.has_next %}
      <li><a href="?page={{ weather.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}

</footer>
{% endblock %}